version: '3.8'

services:
  web:
    build: ./
    command: flask run -h 0.0.0.0
    volumes:
      - ./:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 384M
        reservations:
          cpus: '0.05'
          memory: 128M
  
  database:
    image: postgres:16-alpine
    env_file:
      - .env
    restart: always # reinicia automáticamente quando acontece algum erro
    volumes:
      - db:/var/lib/postgresql/data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./sql/data.sql:/docker-entrypoint-initdb.d/2.sql
    ports:
      - "5432:5432"
volumes:
  db:
    driver: local